### ISSUE TITLE
Create login page

### ISSUE THREAD

**Issue by taylorjohnson141** [taylorjohnson141/rancid-tomatillos#5]
As a user I should be able to see a separate login page which prompts me to  input my username and password.

**Comment by purnima143** [comment]
Can I work on this issue?

**Comment by taylorjohnson141** [comment]
Hey @purnima143 Thanks for reaching out! This project is actually for the bootcamp I am doing right now and they'd get upset if we got outside help. I'd love to collaborate on a project sometime after I finish the bootcamp though!

**Comment by purnima143** [comment]
Okay, no problem :)
